### ISSUE TITLE
Populus Compile Error : "Force_Text"

### ISSUE THREAD

**Issue by blackmoneycoin** [ethereum/populus#450] opened 2018-03-06 01:22 UTC
* Populus Version: 2.2.0
* OS: osx

I am trying to compile contracts with populus and I am getting a "Force_Text" error from eth_utils:

populus comple

Eddies-MBP:Coin edthomas$ populus compile
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/populus", line 11, in <module>
    load_entry_point('populus==2.2.0', 'console_scripts', 'populus')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/populus/__init__.py", line 24, in <module>
    from .project import Project  # NOQA
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/populus/project.py", line 10, in <module>
    from populus.config.defaults import (
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/populus/config/__init__.py", line 1, in <module>
    from .base import (  # noqa: F401
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/populus/config/base.py", line 12, in <module>
    from populus.utils.mappings import (
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/populus/utils/mappings.py", line 8, in <module>
    from eth_utils import (
ImportError: cannot import name 'force_text'

I have installed several times with no effect...

Helpppp.....   Thanks in advanced

http://www.photoandtraveling.com/wp-content/uploads/2013/02/Top-of-the-Monkey-hill.jpg

**Comment by ndj888** [comment] 2018-03-06 14:52
me too

**Comment by ndj888** [comment] 2018-03-06 15:04
python version 3.6.4
[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/populus", line 7, in <module>
    from populus.cli import main
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/populus/__init__.py", line 24, in <module>
    from .project import Project  # NOQA
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/populus/project.py", line 10, in <module>
    from populus.config.defaults import (
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/populus/config/__init__.py", line 1, in <module>
    from .base import (  # noqa: F401
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/populus/config/base.py", line 12, in <module>
    from populus.utils.mappings import (
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/populus/utils/mappings.py", line 8, in <module>
    from eth_utils import (
ImportError: cannot import name 'force_text'](url)

**Comment by blackmoneycoin** [comment] 2018-03-07 01:52
So does this software work or nah!?  I have wasted 2 days trying to get TokenMarketNet to work.   I think I am going back to truffle...  i have no more time to waste...

**Comment by ndj888** [comment] 2018-03-07 03:51
@blackmoneycoin I think the software is Invalid. Becuse i try use Osx system or ubentu system ,same problem.

docker ubentu system

PS E:\docker\poplus> docker run -it my/populus /bin/bash
Traceback (most recent call last):
  File "/usr/local/bin/populus", line 7, in <module>
    from populus.cli import main
  File "/usr/local/lib/python3.5/dist-packages/populus/__init__.py", line 24, in <module>
    from .project import Project  # NOQA
  File "/usr/local/lib/python3.5/dist-packages/populus/project.py", line 10, in <module>
    from populus.config.defaults import (
  File "/usr/local/lib/python3.5/dist-packages/populus/config/__init__.py", line 1, in <module>
    from .base import (  # noqa: F401
  File "/usr/local/lib/python3.5/dist-packages/populus/config/base.py", line 12, in <module>
    from populus.utils.mappings import (
  File "/usr/local/lib/python3.5/dist-packages/populus/utils/mappings.py", line 8, in <module>
    from eth_utils import (
ImportError: cannot import name 'force_text'
PS E:\docker\poplus> docker run -it my/populus
Traceback (most recent call last):
  File "/usr/local/bin/populus", line 7, in <module>
    from populus.cli import main
  File "/usr/local/lib/python3.5/dist-packages/populus/__init__.py", line 24, in <module>
    from .project import Project  # NOQA
  File "/usr/local/lib/python3.5/dist-packages/populus/project.py", line 10, in <module>
    from populus.config.defaults import (
  File "/usr/local/lib/python3.5/dist-packages/populus/config/__init__.py", line 1, in <module>
    from .base import (  # noqa: F401
  File "/usr/local/lib/python3.5/dist-packages/populus/config/base.py", line 12, in <module>
    from populus.utils.mappings import (
  File "/usr/local/lib/python3.5/dist-packages/populus/utils/mappings.py", line 8, in <module>
    from eth_utils import (
ImportError: cannot import name 'force_text'

**Comment by angelano** [comment] 2018-03-07 05:06
The current master doesn't work right now because it uses a deprecated function of eth_utils. See #447 and https://github.com/ethereum/eth-utils/pull/58. If you install previous version of eth_utils, populus will work fine. I think this is a reasonable around before the issue is fixed.

**Comment by tuxxy** [comment] 2018-04-02 00:56
Any update on this? This is really annoying.

**Comment by pipermerriam** [comment] 2018-04-02 20:51
For now, you'll need to try what @santai87 proposed.  Populus is currenly without a maintainer, but that should change in the coming few months.

**Comment by aleczadikian** [comment] 2018-04-06 22:16
This isn't working for me in Python 3. I ran `pip3 install --upgrade populus` and `pip3 install --upgrade web3` and get a similar error when I try to run `populus`:

```
  File "/usr/local/bin/populus", line 7, in <module>
    from populus.cli import main
  File "/usr/local/lib/python3.4/dist-packages/populus/__init__.py", line 24, in <module>
    from .project import Project  # NOQA
  File "/usr/local/lib/python3.4/dist-packages/populus/project.py", line 10, in <module>
    from populus.config.defaults import (
  File "/usr/local/lib/python3.4/dist-packages/populus/config/__init__.py", line 1, in <module>
    from .base import (  # noqa: F401
  File "/usr/local/lib/python3.4/dist-packages/populus/config/base.py", line 12, in <module>
    from populus.utils.mappings import (
  File "/usr/local/lib/python3.4/dist-packages/populus/utils/mappings.py", line 8, in <module>
    from eth_utils import (
ImportError: cannot import name 'force_text'
```

**Comment by volconst** [comment] 2018-04-08 19:38
This worked for me:
pip install eth-utils==0.8.1 web3==3.16.5

**Comment by mikeshultz** [comment] 2018-04-21 20:36
Tried to clean up the dependency issues a little bit but wasn't able to find a set of releases that all worked together.  With some of the newest it seems there's some dependencies that all seem to have issues with pypanadoc in their pypi releases, and until new releases come out, you'll probably have to do the same as me and install these github: 

- [hexbytes](https://github.com/carver/hexbytes)
- [eth-rlp](https://github.com/ethereum/eth-rlp)
- [eth-hash](https://github.com/ethereum/eth-hash)

**Comment by stfairy** [comment] 2018-06-15 04:45
With `pip3 install eth-utils==0.8.1 web3==3.16.5` I couldn't run `py.test tests/`.  Had to run `pip3 install eth-utils==0.7.4`

**Comment by asofyan** [comment] 2018-08-08 03:41
Tried this:
`pip install eth-utils==0.8.1 web3==3.16.5`

pip init is working. but on py.test, it failed again..

`pluggy.manager.PluginValidationError: Plugin 'ethereum' could not be loaded: (eth-utils 0.8.1 (/Users/ahmadsofyan/web/python/.eth/lib/python3.6/site-packages), Requirement.parse('eth-utils==0.7.*'), {'eth-abi'})!`

Is there any development on this?

**Comment by voith** [comment] 2018-08-08 03:45
This will be fixed in #474

**Comment by voith** [comment] 2018-08-08 04:34
I don't. The thing is `populus` has not been maintained for a long time. Wait for a week or two and all the related fixes should get into master.

**Comment by voith** [comment] 2018-08-08 04:41
@asofyan you could probably install from my fork. I have added several fixes to this branch which are combinations of severals PR's that I've opened.
try this:
```
pip install -e git+https://github.com/voith/populus.git@new-populus-ico#egg=populus
```

However, make sure that you have removed other dependencies like `eth-utils`, `web3` from your `requiremenets.txt` or `setup.py`. Also, try to use solidity 0.4.24 if you decide to use my branch.

**Comment by asofyan** [comment] 2018-08-08 22:44
Thanks @voith, will try to use your fork until this merged into master. Appreciated.

**Comment by voith** [comment] 2018-08-09 01:49
@asofyan Note. Try to copy `project.json` from [here](https://github.com/TokenMarketNet/ico/blob/4ad35b3720d695be4a450eb0a3531d1aac07c003/project.json). I've changed the version to 9 and some keys have been removed. If you don't copy project.json from there then you might get some nasty errors.
There's a populus channel on gitter. Feel free to ask me questions there.

**Comment by voith** [comment] 2018-09-03 16:43
This issue was fixed in #474. Please trying installing populus from master.

**Closed by voith** 2018-09-03 16:43 UTC

**Comment by arpi9211** [comment] 2019-02-17 07:40
Populus Version: 2.2.0
OS: osx

**Problem**:
ImportError: cannot import name 'force_bytes' and
pluggy.manager.PluginValidationError: Plugin 'ethereum' could not be loaded: (eth-utils 0.8.1 (/Users/me/web/python/.eth/lib/python3.6/site-packages), Requirement.parse('eth-utils==0.7.*'), {'eth-abi'})!

**solution**:
eth-abi == 0.5.0   
  
changing the versions of eth-utils == 0.8.1 to eth-utils==0.7.4 and web3 == 4.8.2 to web3==3.16.5 solved the issue for me.

command:
$ pip install eth-utils==0.7.4 web3==3.16.5

**Comment by avatar-lavventura** [comment] 2019-04-26 06:50
@voith: How could I install populus from master since its is updated as its not maintained.

Is this proper way to do it: `pip install git+git://github.com/ethereum/populus.git@2ab03fea0d0e2881c80698d2a349a74cc6c953d3 --user` hash is the 2 commits behind the master?
